### ISSUE TITLE
Maybe expose more?

### ISSUE THREAD

**Issue by jakobdalsgaard** [RaghavCodeHub/matrix#8]
Hi,

Would it make sense to expose more functionality than merely 'matrix'?

I'd like to have an identity function be available for example; the export could look like this:

```
module.exports = matrix;
module.exports.identity = (d => matrix(identity(d)));
```

**Comment by raghavgujjar** [comment]
@jakobdalsgaard thanks for the suggestion. There are plans to add [svd](https://en.wikipedia.org/wiki/Singular_value_decomposition) and [pinv](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse). I welcome contributors for these.

**Comment by raghavgujjar** [comment]
@jakobdalsgaard try this https://github.com/RaghavCodeHub/matrix?tab=readme-ov-file#19-generate. 

For generating identity matrix use:
```javascript
matrix.gen(1).diag(3);
```
